syntax = "proto3";
package collection;

import "google/protobuf/struct.proto";

option go_package = "phoenix-marketplace-api/types/collection";

message Collection {
  string id = 1;
  string name = 2;
  string description = 3;
  google.protobuf.Struct metadata = 4;
  uint32 total_items = 5;
}

message CollectionAvailable {
  string id = 1;
  string name = 2;
  uint32 total_items = 3;
  string description = 4;
}

message CollectionPopular {
  string id = 1;
  string name = 2;
  float trade_volume = 3;
  uint32 total_items = 4;
}

message NFT {
  string nid = 1;
  string id = 2;
  google.protobuf.Struct metadata = 3;
}

message CollectionDetail {
  string id = 1;
  string name = 2;
  string description = 3;
  google.protobuf.Struct metadata = 4;
  uint32 total_items = 5;
  repeated NFT nfts = 6;
}

message CollectionsAvailableRequest {}

message CollectionsAvailableResponse { repeated Collection collections = 1; }

message CollectionsPopularRequest {}

message CollectionsPopularResponse {
  repeated CollectionPopular collections = 1;
}

message CollectionsRequest {}

message CollectionsResponse { repeated Collection collections = 1; }

message CollectionDetailRequest { string address = 1; }

message CollectionDetailResponse { CollectionDetail data = 1; }