// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: offer/offer.proto

package offer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Bidder        string                 `protobuf:"bytes,3,opt,name=bidder,proto3" json:"bidder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_offer_offer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_offer_offer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_offer_offer_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *Offer) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Offer) GetBidder() string {
	if x != nil {
		return x.Bidder
	}
	return ""
}

type OffersAtNftRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CollectionAddress string                 `protobuf:"bytes,1,opt,name=collection_address,json=collectionAddress,proto3" json:"collection_address,omitempty"`
	NftId             string                 `protobuf:"bytes,2,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OffersAtNftRequest) Reset() {
	*x = OffersAtNftRequest{}
	mi := &file_offer_offer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffersAtNftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffersAtNftRequest) ProtoMessage() {}

func (x *OffersAtNftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offer_offer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffersAtNftRequest.ProtoReflect.Descriptor instead.
func (*OffersAtNftRequest) Descriptor() ([]byte, []int) {
	return file_offer_offer_proto_rawDescGZIP(), []int{1}
}

func (x *OffersAtNftRequest) GetCollectionAddress() string {
	if x != nil {
		return x.CollectionAddress
	}
	return ""
}

func (x *OffersAtNftRequest) GetNftId() string {
	if x != nil {
		return x.NftId
	}
	return ""
}

type OffersAtNftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*Offer               `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffersAtNftResponse) Reset() {
	*x = OffersAtNftResponse{}
	mi := &file_offer_offer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffersAtNftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffersAtNftResponse) ProtoMessage() {}

func (x *OffersAtNftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offer_offer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffersAtNftResponse.ProtoReflect.Descriptor instead.
func (*OffersAtNftResponse) Descriptor() ([]byte, []int) {
	return file_offer_offer_proto_rawDescGZIP(), []int{2}
}

func (x *OffersAtNftResponse) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

var File_offer_offer_proto protoreflect.FileDescriptor

var file_offer_offer_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x05, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x22, 0x5a, 0x0a, 0x12,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x41, 0x74, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x66, 0x74, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x13, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x73, 0x41, 0x74, 0x4e, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x73, 0x42, 0x64, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x42, 0x0a, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x17, 0x70, 0x68, 0x6f, 0x65, 0x6e, 0x69, 0x78, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x4f, 0x58, 0x58, 0xaa,
	0x02, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0xca, 0x02, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0xe2,
	0x02, 0x11, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_offer_offer_proto_rawDescOnce sync.Once
	file_offer_offer_proto_rawDescData []byte
)

func file_offer_offer_proto_rawDescGZIP() []byte {
	file_offer_offer_proto_rawDescOnce.Do(func() {
		file_offer_offer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_offer_offer_proto_rawDesc), len(file_offer_offer_proto_rawDesc)))
	})
	return file_offer_offer_proto_rawDescData
}

var file_offer_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_offer_offer_proto_goTypes = []any{
	(*Offer)(nil),               // 0: offer.Offer
	(*OffersAtNftRequest)(nil),  // 1: offer.OffersAtNftRequest
	(*OffersAtNftResponse)(nil), // 2: offer.OffersAtNftResponse
}
var file_offer_offer_proto_depIdxs = []int32{
	0, // 0: offer.OffersAtNftResponse.offers:type_name -> offer.Offer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_offer_offer_proto_init() }
func file_offer_offer_proto_init() {
	if File_offer_offer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_offer_offer_proto_rawDesc), len(file_offer_offer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offer_offer_proto_goTypes,
		DependencyIndexes: file_offer_offer_proto_depIdxs,
		MessageInfos:      file_offer_offer_proto_msgTypes,
	}.Build()
	File_offer_offer_proto = out.File
	file_offer_offer_proto_goTypes = nil
	file_offer_offer_proto_depIdxs = nil
}
