// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: offer/query.proto

package offer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OfferQuery_OffersAtNft_FullMethodName = "/offer.OfferQuery/OffersAtNft"
)

// OfferQueryClient is the client API for OfferQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfferQueryClient interface {
	// NftAtAccount queries list nfts at the given offers
	OffersAtNft(ctx context.Context, in *OffersAtNftRequest, opts ...grpc.CallOption) (*OffersAtNftResponse, error)
}

type offerQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewOfferQueryClient(cc grpc.ClientConnInterface) OfferQueryClient {
	return &offerQueryClient{cc}
}

func (c *offerQueryClient) OffersAtNft(ctx context.Context, in *OffersAtNftRequest, opts ...grpc.CallOption) (*OffersAtNftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OffersAtNftResponse)
	err := c.cc.Invoke(ctx, OfferQuery_OffersAtNft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfferQueryServer is the server API for OfferQuery service.
// All implementations must embed UnimplementedOfferQueryServer
// for forward compatibility.
type OfferQueryServer interface {
	// NftAtAccount queries list nfts at the given offers
	OffersAtNft(context.Context, *OffersAtNftRequest) (*OffersAtNftResponse, error)
	mustEmbedUnimplementedOfferQueryServer()
}

// UnimplementedOfferQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOfferQueryServer struct{}

func (UnimplementedOfferQueryServer) OffersAtNft(context.Context, *OffersAtNftRequest) (*OffersAtNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OffersAtNft not implemented")
}
func (UnimplementedOfferQueryServer) mustEmbedUnimplementedOfferQueryServer() {}
func (UnimplementedOfferQueryServer) testEmbeddedByValue()                    {}

// UnsafeOfferQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfferQueryServer will
// result in compilation errors.
type UnsafeOfferQueryServer interface {
	mustEmbedUnimplementedOfferQueryServer()
}

func RegisterOfferQueryServer(s grpc.ServiceRegistrar, srv OfferQueryServer) {
	// If the following call pancis, it indicates UnimplementedOfferQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OfferQuery_ServiceDesc, srv)
}

func _OfferQuery_OffersAtNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffersAtNftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferQueryServer).OffersAtNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfferQuery_OffersAtNft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferQueryServer).OffersAtNft(ctx, req.(*OffersAtNftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OfferQuery_ServiceDesc is the grpc.ServiceDesc for OfferQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfferQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "offer.OfferQuery",
	HandlerType: (*OfferQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OffersAtNft",
			Handler:    _OfferQuery_OffersAtNft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offer/query.proto",
}
