// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: auction/query.proto

/*
Package auction is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package auction

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_AuctionQuery_AuctionsAvailable_0(ctx context.Context, marshaler runtime.Marshaler, client AuctionQueryClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq AuctionsAvailableRequest
	var metadata runtime.ServerMetadata

	msg, err := client.AuctionsAvailable(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_AuctionQuery_AuctionsAvailable_0(ctx context.Context, marshaler runtime.Marshaler, server AuctionQueryServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq AuctionsAvailableRequest
	var metadata runtime.ServerMetadata

	msg, err := server.AuctionsAvailable(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterAuctionQueryHandlerServer registers the http handlers for service AuctionQuery to "mux".
// UnaryRPC     :call AuctionQueryServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterAuctionQueryHandlerFromEndpoint instead.
func RegisterAuctionQueryHandlerServer(ctx context.Context, mux *runtime.ServeMux, server AuctionQueryServer) error {

	mux.Handle("GET", pattern_AuctionQuery_AuctionsAvailable_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/auction.AuctionQuery/AuctionsAvailable", runtime.WithHTTPPathPattern("/marketplace/auctions/active"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_AuctionQuery_AuctionsAvailable_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AuctionQuery_AuctionsAvailable_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterAuctionQueryHandlerFromEndpoint is same as RegisterAuctionQueryHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterAuctionQueryHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterAuctionQueryHandler(ctx, mux, conn)
}

// RegisterAuctionQueryHandler registers the http handlers for service AuctionQuery to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterAuctionQueryHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterAuctionQueryHandlerClient(ctx, mux, NewAuctionQueryClient(conn))
}

// RegisterAuctionQueryHandlerClient registers the http handlers for service AuctionQuery
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "AuctionQueryClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "AuctionQueryClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "AuctionQueryClient" to call the correct interceptors.
func RegisterAuctionQueryHandlerClient(ctx context.Context, mux *runtime.ServeMux, client AuctionQueryClient) error {

	mux.Handle("GET", pattern_AuctionQuery_AuctionsAvailable_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/auction.AuctionQuery/AuctionsAvailable", runtime.WithHTTPPathPattern("/marketplace/auctions/active"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AuctionQuery_AuctionsAvailable_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AuctionQuery_AuctionsAvailable_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_AuctionQuery_AuctionsAvailable_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"marketplace", "auctions", "active"}, ""))
)

var (
	forward_AuctionQuery_AuctionsAvailable_0 = runtime.ForwardResponseMessage
)
