syntax = "proto3";
package auction;

import "google/api/annotations.proto";
import "auction/auction.proto";

option go_package = "phoenix-marketplace-api/types/auction";

service AuctionQuery {
  rpc AuctionsAvailable(AuctionsAvailableRequest)
      returns (AuctionsAvailableResponse) {
    option (google.api.http).get = "/marketplace/auctions/active";
  }
  rpc Auctions(AuctionsRequest)
      returns (AuctionsResponse) {
    option (google.api.http).get = "/marketplace/auctions";
  }
  rpc AuctionDetail(AuctionDetailRequest) returns (AuctionDetailResponse) {
    option (google.api.http).get = "/marketplace/auction/{auction_id}";
  }
}
